# Generated by Django 4.2.30 on 2026-05-07 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotpverifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpverifications',
            name='attapts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userotpverifications',
            name='error_expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
