# Generated by Django 4.2.30 on 2026-05-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userotpverifications_attapts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpverifications',
            name='error_expired_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
