# Generated by Django 4.2.30 on 2026-05-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userotpverifications_error_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpverifications',
            name='error_expired_at',
            field=models.DateTimeField(),
        ),
    ]
