# Generated by Django 4.2.30 on 2026-05-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userotpidverifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpverifications',
            name='resend_attapts',
            field=models.IntegerField(default=0),
        ),
    ]
