# Generated by Django 4.2.30 on 2026-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userotpverifications_resend_attapts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpverifications',
            name='for_forget_password',
            field=models.BooleanField(default=False),
        ),
    ]
