# Generated by Django 4.2.30 on 2026-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userotpverifications_for_forget_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpverifications',
            name='for_forget_password_verified',
            field=models.BooleanField(default=False),
        ),
    ]
