# Generated by Django 4.2.30 on 2026-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_changepasswordlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepasswordlogs',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
