# Generated by Django 4.2.30 on 2026-05-16 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_changepasswordlogs_is_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEmailLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expired_at', models.DateTimeField()),
                ('attapts', models.IntegerField(default=0)),
                ('error_expired_at', models.DateTimeField()),
                ('is_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
