# Generated by Django 4.2.30 on 2026-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_changeemaillogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeemaillogs',
            name='new_email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
