# Generated by Django 4.2.30 on 2026-05-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_changeemaillogs_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeemaillogs',
            name='old_email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
