# Generated by Django 4.2.30 on 2026-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_changeemaillogs_old_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeemaillogs',
            name='resend_attapts',
            field=models.IntegerField(default=0),
        ),
    ]
